name: CI Neo

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: "30 7 * * 0"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  FQDN: azurecr.io
  DOCKERFILE_ROOT: apps
  PROJECT: neo

jobs:
  build-push-neo-images:
    strategy:
      matrix:
        include:
          - app: api
            arch: amd
            os: ubuntu-latest
          - app: api
            arch: arm
            os: ubuntu-latest-arm
          - app: orchestrator
            arch: amd
            os: ubuntu-latest
          - app: orchestrator
            arch: arm
            os: ubuntu-latest-arm
          - app: planner
            arch: amd
            os: ubuntu-latest
          - app: planner
            arch: arm
            os: ubuntu-latest-arm
          - app: agents
            arch: amd
            os: ubuntu-latest
          - app: agents
            arch: arm
            os: ubuntu-latest-arm
          - app: customer
            arch: amd
            os: ubuntu-latest
          - app: customer
            arch: arm
            os: ubuntu-latest-arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Generate JWT
        id: generate_jwt
        run: |
          APP_ID=1560053
          PRIVATE_KEY="${{ secrets.GH_APP_SECRET }}"
          IAT=$(date +%s)
          EXP=$((IAT + 540))
          HEADER='{"alg":"RS256","typ":"JWT"}'
          PAYLOAD="{\"iat\":$IAT,\"exp\":$EXP,\"iss\":$APP_ID}"
          base64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }
          ENCODED_HEADER=$(echo -n "$HEADER" | base64url)
          ENCODED_PAYLOAD=$(echo -n "$PAYLOAD" | base64url)
          SIGNATURE=$(echo -n "${ENCODED_HEADER}.${ENCODED_PAYLOAD}" | \
            openssl dgst -sha256 -sign <(echo "$PRIVATE_KEY") | \
            base64url)
          JWT="${ENCODED_HEADER}.${ENCODED_PAYLOAD}.${SIGNATURE}"
          echo "jwt=$JWT" >> $GITHUB_OUTPUT

      - name: Get App Token
        id: get_token
        run: |
          INSTALLATION_ID=75078289
          TOKEN=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ steps.generate_jwt.outputs.jwt }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens | jq -r .token)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Set environment-specific variables
        id: env_config
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "registry=pprodnbtregistry" >> $GITHUB_OUTPUT
            echo "subscription=${{ secrets.AZURE_SUBSCRIPTION_ID_PPROD }}" >> $GITHUB_OUTPUT
          else
            echo "registry=nbtreg" >> $GITHUB_OUTPUT
            echo "subscription=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Neo repo
        uses: actions/checkout@v4
        with:
          repository: Numbr-Tech/Neo
          token: ${{ steps.get_token.outputs.token }}
          ref: dev

      - name: Bazel build image
        run: |
          bazel run //apps/${{ matrix.app }}:${{ matrix.app }}_load

      - name: Retag Bazel image for ACR push
        id: set-tag
        run: |
          SOURCE_IMAGE="${{ env.PROJECT }}-${{ matrix.app }}"
          IMAGE_TAG="${{ matrix.arch }}-${{ github.sha }}"
          docker tag $SOURCE_IMAGE
          base-tag= $SOURCE_IMAGE >> "$GITHUB_OUTPUT"

      # - name: Log in to Azure with federated credentials
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ steps.env_config.outputs.subscription }}

      # - name: Log in to Azure Container Registry
      #   run: az acr login --name ${{ steps.env_config.outputs.registry }}

# - name: Push Docker image
#   run: docker push ${{ env.TARGET_IMAGE }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            #role-to-assume: ${{ inputs.aws-role-to-assume }}
            role-to-assume: "arn:aws:iam::851725266353:role/neo_github_oidc_role"
            #role-session-name: ${{ inputs.aws-role-session-name }}
            role-session-name: "neo-backend-cd"
            #aws-region: ${{ inputs.aws-region }}
            aws-region: "eu-central-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Check if image already exists
      #   id: publish-required
      #   continue-on-error: true
      #   run: .github/scripts/find-ecr-image.sh ${{ inputs.ecr-repository }} ${{ matrix.arch }}-${{ needs.set-vars.outputs.base-tag }}

  create-push-manifest:
    name: Push manifest for ${{ inputs.ecr-repository }}
    runs-on: ubuntu-latest
    defaults:
        run:
            shell: bash
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ inputs.aws-role-to-assume }}
            role-session-name: ${{ inputs.aws-role-session-name }}
            aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create and push manifest
        uses: Noelware/docker-manifest-action@0.4.3
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            #ECR_REPOSITORY: ${{ inputs.ecr-repository }}
            ECR_REPOSITORY: "neo-api-docker"
            BASE_TAG: ${{ needs.set-vars.outputs.base-tag }}
        with:
            inputs: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.BASE_TAG }}
            images: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:amd-${{ env.BASE_TAG }},${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:arm-${{ env.BASE_TAG }}
            push: true
